use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'markymark_Example' do
    pod 'markymark', :path => '../'
    pod 'SwiftLint'
end

target 'markymark_Tests' do
    inherit! :search_paths
    pod 'markymark', :path => '../'
end

target 'TodayExtension' do
    inherit! :search_paths
    pod 'markymark', :path => '../'
end
