use_frameworks!

target 'markymark_Example' do
    pod 'markymark', :path => '../'
end

target 'markymark_Tests' do
    inherit! :search_paths
    pod 'markymark', :path => '../'
end

target 'TodayExtension' do
    inherit! :search_paths
    pod 'markymark', :path => '../'
end
