# Swiftlint currently still fails, disabled for now
os: osx
language: swift
xcode_project: MarkyMark.xcodeproj
xcode_scheme: markymark_Tests
osx_image: xcode11
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
script:
- swift build -Xswiftc "-sdk" -Xswiftc $(xcrun --sdk iphonesimulator --show-sdk-path) -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
- set -o pipefail && xcodebuild test -workspace Example/markymark.xcworkspace -scheme markymark-Example -destination 'platform=iOS Simulator,name=iPhone 11' | xcpretty
# - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
